### ISSUE TITLE
can show page controller with this one?

### ISSUE THREAD

**Issue by maulik6994** [superpeteblaze/ScalingCarousel#10]
I have to show page indicater with this scrolling will be able to do?

**Comment by maulik6994** [comment]
i mean how to get current page with scrolling

**Comment by abdulla-allaith-7** [comment]
+1 should have a variable to know which cell is the current one.

**Comment by rankinit** [comment]
Does anyone have a solution for this issue?  Thanks!

**Comment by superpeteblaze** [comment]
@maulik6994 @abdulla-allaith @rankinit This feature will be released as part of the upcoming 'Swift 4' release.  

See the Swift 4 branch here - https://github.com/superpeteblaze/ScalingCarousel/blob/psmith/Swift4/ScalingCarousel/Classes/ScalingCarouselView.swift

**Comment by rankinit** [comment]
@superpeteblaze  - Which part of the code will have this new feature?  Can I use with Swift 3 source?

Thanks!!

**Comment by superpeteblaze** [comment]
Just released v2 with requested functionality included. Closing this.
