### ISSUE TITLE
Visible cell ?

### ISSUE THREAD

**Issue by dx777** [superpeteblaze/ScalingCarousel#12]
How can i get callback, when visible cell is changed, in didscroll method ? 
Than how can i get indexpath, of centered visible cell ?
In Bikey gif, content is changed in background,when cell is swiped, i wonder how can i do same ?

**Comment by DpzAtMicRO** [comment]
Yes, much needed feature. Any solution expected?

**Comment by superpeteblaze** [comment]
This will be part of the upcoming Swift 4 release

**Comment by dx777** [comment]
I managed to did this, using this method:
https://stackoverflow.com/questions/19265655/how-to-get-indexpath-for-cell-which-is-located-in-the-center-of-uicollectionview
