### ISSUE TITLE
Missing function central index

### ISSUE THREAD

**Issue by anshulmahipal** [superpeteblaze/ScalingCarousel#16]
Hello, 
   /Users/apple/Documents/Range/Range/controllers/PropertyNearByViewController.swift:398:13: Value of type 'ScalingCarouselView' has no member 'currentCenterCellIndex'
when try to use your libraray as pod

**Comment by superpeteblaze** [comment]
Hi,

Are you using the latest release of the pod? Maybe you need to run 'pod repo update’.

**Comment by anshulmahipal** [comment]
I did already

**Comment by superpeteblaze** [comment]
And what do you see when you look in ScalingCarouselView? Is the property there?

**Comment by anshulmahipal** [comment]
At time of download, I get the property but on time of download dependencies property is not there

**Comment by superpeteblaze** [comment]
The issue is now solved.

I have created a new release - v2.0.1. To get the latest, run the following:

- pod repo update
- pod update

You should see Cocoapods installing version v2.0.1.

Pete
