### ISSUE TITLE
Pod out of date

### ISSUE THREAD

**Issue by cs-joao-souza** [superpeteblaze/ScalingCarousel#17]
Please, update Pod because the source code is not the same.

**Comment by superpeteblaze** [comment]
Hi,

I have created a new release - v2.0.1. To get the latest, run the following:

- pod repo update
- pod update

You should see Cocoapods installing version v2.0.1..

Please let me know if this solves the issue.

Pete

**Comment by cs-joao-souza** [comment]
Nice.

It have worked.

Thanks
