### ISSUE TITLE
Circular/Chain carousel

### ISSUE THREAD

**Issue by skander300** [superpeteblaze/ScalingCarousel#21]
Is there a way to make ScalingCarousel circular == > the element after the last one is the first one ?
Any help ?

**Comment by superpeteblaze** [comment]
You should be able to design/layout your cell to be any shape you wish. However, scaling may not work as exactly expected.

**Comment by skander300** [comment]
No no, you misunderstood me.
I am not talking about circular shape.
I am talking about a chain carousel, means when i swipe to the last element , the next element will be the first element.

**Comment by superpeteblaze** [comment]
There is nothing in ScalingCarousel that would prevent this. You could implement this just by supplying the right data to the UICollectionView, via the UICollectionViewDatasource methods
