### ISSUE TITLE
ScalingCarousel in UICollectionView with horizontal scroll

### ISSUE THREAD

**Issue by aspek** [superpeteblaze/ScalingCarousel#22]
Hi @superpeteblaze, Thanks you for your frameworks. First thing I want to tell I'm not good in english language. 

I have an issue with ScalingCarousel in UICollectionView with horizontal scrolling.

**issue is.**
CollectionView  = C  ---->  C has 3 Cells 
ScalingCarousel = S ---->  S is a cell. It's the one of them

in this case  index of "S" is 0

1.  if you swipe the card in the "S" to the last index  and swipe it again to the next cell of "C" It will use "C" scrollview and "S" scrollview function at the same time.
2 . repeat step 1 but do in quickly "S" can't scroll anymore

**solved.**
in case 1 
```
public func scrollViewDidScroll(_ scrollView: UIScrollView) {
           /*
             Move the ScalingCarousel base d on the
             contentOffset of the 'invisible' UIScrollView
             */

        if scrollView == invisibleScrollView  {
            // Also, this is where we scale our cells
            for cell in visibleCells {
                if let infoCardCell = cell as? ScalingCarouselCell {
                    infoCardCell.scale(withCarouselInset: inset)
                }
            }
        }
        updateOffSet()
    }
```
but for 2. I can't resolve with the best way. I just avoid `bounces` set `invisibleScrollView.bounces = false`

**Comment by superpeteblaze** [comment]
Did you make any progress with this issue @aspek?

**Comment by aspek** [comment]
Nope, i have already unistalled form my project. I’m using default style from uicollectionview sorry for that.

**Comment by superpeteblaze** [comment]
No problem 👍🏽
