### ISSUE TITLE
Configure cornerRadius

### ISSUE THREAD

**Issue by iamabhiee** [superpeteblaze/ScalingCarousel#23]
Is there any way to configure cornerRadius of mainView?

**Comment by superpeteblaze** [comment]
Yes, one way would be to override §`open func scale(carouselInset:scaleMinimum:)` and specify your own corner radius.

**Comment by tanand7** [comment]
Is the above mentioned method works? Not for me. I have an imageview inside the cell. I want to see the entire cell with rounded corner but it's not working. I gave corner radius of 50 it works but not eat one. can someone help me
