### ISSUE TITLE
RTL issue

### ISSUE THREAD

**Issue by iamabhiee** [superpeteblaze/ScalingCarousel#24]
Fantastic library but for RTL its not working properly

**Comment by superpeteblaze** [comment]
Thanks @iamabhiee. Can you detail exactly what the issues are, it would help.

**Comment by iamabhiee** [comment]
In RTL language carousel direction should be from Right to left but it’s Left to right only

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by superpeteblaze** [comment]
ScalingCarousel is a subtype of UICollectionView, so we should be able to use the `semanticContentAttribute` property of UIView to solve this. 

Docs - https://developer.apple.com/documentation/uikit/uiview/1622461-semanticcontentattribute

**Comment by iamabhiee** [comment]
I tried to set that but it’s not working, you can try setting it forceRightToLeft

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by superpeteblaze** [comment]
Thats interesting, I assumed that would work.

It’s not something I can look at right now, but if you want to look in to it, and you find a solution, maybe could open a PR on ScalingCarousel. I’d be happy to review.

**Comment by iamabhiee** [comment]
I’ve used another carousel in another app but there it’s working fine I’ll try and see if I could fix

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by superpeteblaze** [comment]
Awesome, hopefully you find something.
