### ISSUE TITLE
Easy way to start on a specific element?

### ISSUE THREAD

**Issue by JulianHunt** [superpeteblaze/ScalingCarousel#30]
Two questions/possible request that I may fork and implement myself or open a PR to add this functionality if there is no current way to do this easily. 

-Is it possible to start scrolled to a specific index? I have a three element carousel and want to start on the middle (2nd element)

-Secondly, is it possible to enable tap to scroll? Ideally if I tap on the left side it should scroll to the next element towards the left, If I tap to the right it would scroll to the next element to the right.

Cheers,
Julian

**Comment by superpeteblaze** [comment]
Hi Julian,

Thanks for getting in touch.

I always welcome contributions to ScalingCarousel, and would be happy to review any PRs.

In relation to the specific functionality you mention:

1. It is possible to start scrolled to a specific index. I actually do this myself using 

scalingCarousel.scrollToItem(at: indexPath, at: .top, animated: animated)

Maybe you can try this.

2. I am unsure about tap to scroll. Maybe you could try and let me know. If it requires a PR, we can do that.

Best,
Pete
