### ISSUE TITLE
Too many animations are taking place at one time

### ISSUE THREAD

**Issue by MaeseppTarvo** [superpeteblaze/ScalingCarousel#31]
Hey, I tried your example project but it has only black screen and gives the following in the console:

> ScalingCarousel_Example[65453:1493416] +[CATransaction synchronize] called within transaction

**Comment by superpeteblaze** [comment]
I have not seen this, can you provide a sample project demonstrating this issue please?

**Comment by superpeteblaze** [comment]
See this now @MaeseppTarvo, thanks, will look to fix

**Comment by superpeteblaze** [comment]
Hi @MaeseppTarvo, I just release version 2.2 of ScalingCarousel, which fixes the 'black screen' issue. It was not caused by the error message in the console. This error message is still present, but does not affect the example project.
