### ISSUE TITLE
Change spacing between cells

### ISSUE THREAD

**Issue by Alqueraf** [superpeteblaze/ScalingCarousel#32]
Hello, any chance to modify minimumLineSpacing and minimumInteritemSpacing? I am trying to modify them by extending the files up to ScalingCarouselLayout but I end up with private functions.

Thanks.

**Comment by superpeteblaze** [comment]
Can't you override the `prepare` method of `ScalingCarouselLayout`, call `super.prepare`, and then update the `minimumLineSpacing` and `minimumInteritemSpacing`?

**Comment by Alqueraf** [comment]
Hey, yes, but how can I set my custom Layout class to the ScalingCarouselView?

**Comment by Alqueraf** [comment]
The convenience init is never called. I am using it from the storyboard

**Comment by superpeteblaze** [comment]
Cool. That’s no problem. In the storyboard, you should be able to specify the layout class that you want.

**Comment by Alqueraf** [comment]
Yes, but it is replaced via code on the configureLayout() method anyway which has private access, and I cannot override the inset variable either which is calls it on the didSet

**Comment by superpeteblaze** [comment]
I understand. I don’t have time right now to make changes to ScalingCarousel, but, if you can identify a change which would help you, I am happy to accept pull requests.

**Comment by Alqueraf** [comment]
Great, thank you!

**Comment by superpeteblaze** [comment]
Looked in to this @Alqueraf. 

The functionality you desire can be achieved by conforming to `UICollectionViewDelegateFlowLayout`, and implementing the two methods below. When your conform to this protocol, the `collectionViewLayout` will use the values returned from these functions.

```
extension YourViewController: UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        
        return 0
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumInteritemSpacingForSectionAt section: Int) -> CGFloat {
        
        return 0
    }
}
```

I'll close this issue, as no changes are needed to the library.
