### ISSUE TITLE
Pagination for collection item

### ISSUE THREAD

**Issue by snc001** [superpeteblaze/ScalingCarousel#36]
I was wondering - is there a way to add pagination so that the user knows how many items are in the carousel as well as the index that they're on??

**Comment by superpeteblaze** [comment]
Hi @snc001, currently, no, this is not a feature. I don't have any immediate plans to add this. However, if you would like to propose an implementation, and open a pull request, I would be happy to consider adding it.

**Comment by superpeteblaze** [comment]
Closing due to no response
