### ISSUE TITLE
Wrong resizing Cell on Device rotate

### ISSUE THREAD

**Issue by pabsanmez** [superpeteblaze/ScalingCarousel#38]
Hi! I am rotating one iPhone 7 and the carousel is not working fine.

![carouselworking](https://user-images.githubusercontent.com/20070596/40588454-b391bc16-61dd-11e8-96c8-14ad84582c58.jpg)
![carouselnotworking](https://user-images.githubusercontent.com/20070596/40588461-bccafe14-61dd-11e8-8071-bc9df8c6b623.jpg)

In the view inspector we see that the ScrollView has the right value but not the inside View, also the View that is inside the Cell has the right frame, the one that fails is the deeper view.
![captura de pantalla 2018-05-27 a las 18 40 39](https://user-images.githubusercontent.com/20070596/40588462-bf019a26-61dd-11e8-84c5-d339bd846b63.png)

I have tried to invalidate the flowLayout, to reload data and to call didScroll in the viewWillTransition and in the viewDidLayoutSubviews, but it didn't solve my issue :(.

The mainView.frame is failing in the ScalingCarouselCell

(I have tried your example and it is not working right neither, it happens to me what happens in your code version)

**Comment by pabsanmez** [comment]
I almost have it!

I copied your example project and this was your code for the Cell (And the one that it is in the Readme)

``` swift
    override init(frame: CGRect) {
        super.init(frame: frame)

        mainView = UIView(frame: contentView.bounds)
        contentView.addSubview(mainView)
    }
```

I have added `mainView.fillSuperview()`.

Where the method fillSuperview is:

``` swift
   func fillSuperview(withEdges edges: UIEdgeInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)) {
        guard let superView = superview else { return }

        translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            leadingAnchor.constraint(equalTo: superView.leadingAnchor, constant: edges.left),
            trailingAnchor.constraint(equalTo: superView.trailingAnchor, constant: -edges.right),
            topAnchor.constraint(equalTo: superView.topAnchor, constant: edges.top),
            bottomAnchor.constraint(equalTo: superView.bottomAnchor, constant: -edges.bottom)
            ])
    }
```

**Comment by pabsanmez** [comment]
Fixed! I have opened a MR :)

**Comment by superpeteblaze** [comment]
Awesome! Looking at PR now @pabsanmez

**Comment by superpeteblaze** [comment]
@pabsanmez What's your twitter handle?

**Comment by pabsanmez** [comment]
@superpeteblaze I do not use twitter :( hahaha

**Comment by superpeteblaze** [comment]
Ok, no problem. Wanted to know as I announce new versions on twitter. Thanks for the contribution, version 2.3 is now released. 🚀
