### ISSUE TITLE
Avoid scrolling to the wrong position when tapping the item

### ISSUE THREAD

**Issue by anafinotti** [superpeteblaze/ScalingCarousel#40]
add..
  
 func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {

        collectionView.scrollToItem(at: indexPath, at: .centeredHorizontally, animated: true)

    }

**Comment by superpeteblaze** [comment]
👋🏽 @anafinotti. Is this a fix for an issue you have seen?

**Comment by pabsanmez** [comment]
I use this method too when I select an item programmatically, It just center horizontally the item that you have chosen, but I think is the logical way of using it 

`        carousel.scrollToItem(at: IndexPath(row: index, section: 0), at: .centeredHorizontally, animated: true)`

**Comment by superpeteblaze** [comment]
@anafinotti & @pabsanmez, thanks for the help with this. Could you explain the problem a bit more?

**Comment by pabsanmez** [comment]
the line of code that I have written is the same than hers hahahaha, but I only send the row and not the section, What I suggest is creating a method that has the .centeredHorizontally by default so the user only has to set the indexPath and if they want it animated or not :)

**Comment by mwawrusch** [comment]
Guys, I have a problem that might be related. When initializing the view (in viewDidLoad)
```
        scalingCarousel!.scrollToItem(at: IndexPath(row: itemToShow, section: 0), at: .centeredHorizontally, animated: false)
        scalingCarousel!.deviceRotated()
```
messes up the right item. It works fine when I scroll to  element 0 though:

![img_c176ed739e19-1](https://user-images.githubusercontent.com/481276/41207148-6557abf8-6cc5-11e8-8c3f-f4c5f07a308c.jpeg)

**Comment by superpeteblaze** [comment]
Ok @pabsanmez, I understand. It's a good suggestion but I don't think it adds a great amount of value, so I think we can leave it for the moment.

**Comment by superpeteblaze** [comment]
@mwawrusch, thanks for pointing this out. Could you possibly open a separate issue for this? Then we can plan to fix it.

**Comment by superpeteblaze** [comment]
Closing this, as not planning to implement suggestion at this time
