### ISSUE TITLE
Cells sometimes rendered wrong on scrolling

### ISSUE THREAD

**Issue by MarcoStuurman** [superpeteblaze/ScalingCarousel#43]
Hi,

I've used this awesome project in one of mine, but when I scroll, there is a small chance the corners of the cell are not rounded and the inset is not applied. Check out the video below for clarification on what I mean:

https://www.youtube.com/watch?v=WHP0k6V5Mb4

This also happens in the example project compiled to my phone.

![image](https://user-images.githubusercontent.com/1322541/45254450-a7f37d80-b378-11e8-91e2-bc4ba2b2b673.png)

**Comment by superpeteblaze** [comment]
Thanks for opening the issue @MarcoStuurman. If I get time I’ll look in to it. Alternatively, if you come across a solution, it would be great if you could open a PR.

**Comment by MarcoStuurman** [comment]
Hi @superpeteblaze I think I’m not really finding my way around in Swift well enough yet to find the problem, but I’ll try to look for it soon

**Comment by SaezChristopher** [comment]
any news for this?

**Comment by superpeteblaze** [comment]
No news yet @SaezChristopher. I have not found the time to look at this, so at the moment, hoping for some help from the community.

**Comment by MacMichas** [comment]
Hi, I think I might discovered the problem based on this comment: https://stackoverflow.com/a/13604032

Actualy, **you can refactor the enterly math based in the solution that was proposed**, or a alternative way is to:

1: Call the "collection.reloadData()"
2: Manualy Invalidates the current layout of the cell, forcing them to redraw everything with calling the "cell.setNeedsLayout()" at the end of the "cellForItemAt indexPath: IndexPath" function.  

I hope I have helped you with something, it worked for me, 👍🏻.

**Comment by superpeteblaze** [comment]
Awesome! Thanks for letting us know @MacMichas 🙌🏼. 

CC @MarcoStuurman @SaezChristopher if you try this an it work's, I'll close this issue.

**Comment by avivInmanage** [comment]
didnt work....

**Comment by MacMichas** [comment]
Hi aviv..

Can you post your code? I ran tests now and it worked the way I instructed it in the post above.

**Comment by DpzAtMicRO** [comment]
@MacMichas Cool, that solves the issue. Awesome.
