### ISSUE TITLE
Question: How can I make the item start from center when it loaded ?

### ISSUE THREAD

**Issue by kristoff2016** [superpeteblaze/ScalingCarousel#44]
Hello, thanks for sharing great plugin.
I want to make it start from center of all the items 
Please tell me how can I make it ? or do you have any option for it ?

thank you

**Comment by superpeteblaze** [comment]
Hi @kristoff2016. Sure, you can start from whatever cell you like by calling the following method on ScalingCarouselView:

```
 func scrollToItem(at indexPath: IndexPath, at scrollPosition: UICollectionViewScrollPosition, animated: Bool)
```

**Comment by kristoff2016** [comment]
Thank you so much for your replied! Will try and close it when I had it done
Thank you again!

**Comment by kristoff2016** [comment]
Hello, 
Like am an "idiot".

```
func scrollToItem(at indexPath: IndexPath, at scrollPosition: UICollectionView.ScrollPosition, animated: Bool){
           scalingCarousel.scrollToItem(at: IndexPath(item: 3, section: 0), at: .right, animated: true)

    }

override func scrollViewDidScroll(_ scrollView: UIScrollView) {
        //scalingCarousel.didScroll()

    }
```
it does not work

thank you

**Comment by kristoff2016** [comment]
Example I have 3 items and index start from 0,1,2 what I want to do it cell will be started at index 1 of all cells items 
thank you for your helped
