### ISSUE TITLE
SwiftPM support

### ISSUE THREAD

**Issue by TofPlay** [superpeteblaze/ScalingCarousel#5]
[SwiftPM](https://goo.gl/E01ufX) is Swift's official package manager. In the near future it will replace Carthage and CocoaPods.

Here some articles about SwiftPM:
* [An Introduction to the Swift Package Manager](https://goo.gl/byiOc6)
* [Swift Dependency Management for iOS](https://goo.gl/7eaz1A)
* [Getting Started with Swift Package Manager (SwiftPM)](https://goo.gl/rCHeQU)
* [Swift.org: Package Manager](https://goo.gl/E01ufX)

When your component is compatible with SwiftPM add on your `README.md` [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://goo.gl/E01ufX) badge on top and add a section for the installation with SwiftPM.

**Comment by superpeteblaze** [comment]
Swift PM does not yet support iOS projects. Closing this for now.
