### ISSUE TITLE
I put button in Cell but when I tap on Button that time cell scroll and not proper display.

### ISSUE THREAD

**Issue by patelravi20** [superpeteblaze/ScalingCarousel#50]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/41731250/47999723-735a3300-e129-11e8-8838-fb1ac57ec932.gif)

**Comment by superpeteblaze** [comment]
Hi @patelravi20, I’m currently not free to work on this. If you find a solution, I’d be happy to accept a PR.

**Comment by vishalkalola1** [comment]
hey @patelravi20 and @superpeteblaze 
You need to add isPagingEnabled = true and isScrollEnabled = false in your code

**Comment by superpeteblaze** [comment]
Thanks @vishalkalola1 🙌🏼
