### ISSUE TITLE
Avoid scrolling to the wrong position when tapping Middle Cell?

### ISSUE THREAD

**Issue by kirollosmagedy** [superpeteblaze/ScalingCarousel#52]
<img width="342" alt="screen shot 2018-11-07 at 5 14 59 pm" src="https://user-images.githubusercontent.com/12835439/48140058-b0046680-e2b0-11e8-8f60-69e676846535.png">

**Comment by superpeteblaze** [comment]
No update @Smnelson13. I’m not currently available to work on this. If you find a solution, it would be awesome if you could open a PR.

**Comment by vishalkalola1** [comment]
@kirollosmagedy @Smnelson13   You need to add isPagingEnabled = true and isScrollEnabled = false in your code OR Property of UICollectionView isPagingEnabled = Enable and isScrollEnabled = disable see below image
<img width="772" alt="screenshot 2018-11-19 at 5 34 22 pm" src="https://user-images.githubusercontent.com/26406461/48706189-7ffa8300-ec21-11e8-8779-3422eadf160b.png">

**Comment by superpeteblaze** [comment]
Thanks @vishalkalola1

**Comment by superpeteblaze** [comment]
Fixed in latest release - https://github.com/superpeteblaze/ScalingCarousel/releases/tag/v3.0.1
