### ISSUE TITLE
UIButton inside Cell

### ISSUE THREAD

**Issue by dogo** [superpeteblaze/ScalingCarousel#53]
When we have a UIButton inside the cell, the touchUpInside event trigger the scrollViewDidScroll, moving the cell.

like this:

![simulator screen shot - iphone 8 - 2018-11-27 at 17 08 45](https://user-images.githubusercontent.com/1487375/49108522-2587a500-f267-11e8-9098-1482677e7d79.png)

How to avoid this behaviour?

**Comment by superpeteblaze** [comment]
@dogo See here https://github.com/superpeteblaze/ScalingCarousel/issues/50

**Comment by dogo** [comment]
@superpeteblaze I saw this issue and I'm using the suggested path as you can see :

<img width="621" alt="captura de pantalla 2018-11-28 a la s 15 37 48" src="https://user-images.githubusercontent.com/1487375/49173927-c8055e00-f323-11e8-86ad-0421f81c8b47.png">

It can be reproduced in the sample (Attached) 
[ScalingCarousel-master-UIButton.zip](https://github.com/superpeteblaze/ScalingCarousel/files/2626179/ScalingCarousel-master-UIButton.zip)

To reproduce scroll to the second cell and than click on "Button" than go back to the previous screen

**Comment by superpeteblaze** [comment]
Ok, thanks @dogo.

**Comment by dogo** [comment]
@superpeteblaze Good news, I was trying to fix the issue and I realised "The fix is simple, just read the doc"


``` swift
typealias CarouselDelegate = StoryboardViewController
extension StoryboardViewController: UICollectionViewDelegate {
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        
        carousel.didScroll() // <------ 
        
        guard let currentCenterIndex = carousel.currentCenterCellIndex?.row else { return }
        
        output.text = String(describing: currentCenterIndex)
    }
} 
```

Doc : 

`     This method should ALWAYS be called from the ScalingCarousel delegate when
     the UIScrollViewDelegate scrollViewDidScroll(_:) method is called`

Everthing is fine now :D

**Comment by superpeteblaze** [comment]
Awesome @dogo 🙌🏽

**Comment by Rahul379** [comment]
Still facing issue for second cell, but working fine for other cells.
When on second cell after navigating back cell is centered but row value is return 0 which should be 1.

Below code for reference:
func scrollViewDidScroll(_ scrollView: UIScrollView) {
carouselView.didScroll()
guard let currentCenterIndex = carouselView.currentCenterCellIndex?.row else { return }
print(currentCenterIndex)
pageControl.currentPage = currentCenterIndex
}

**Comment by quaringonzalo** [comment]
I recomend use this method. This event don't execute when other page dissapear or click button 

func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        guard let currentCenterIndex = getCollectionView().currentCenterCellIndex else {
            return
        }
        
        delegate?.onCardSelectedChange(card: cards[currentCenterIndex.row])
    }
