### ISSUE TITLE
Support for ios 9

### ISSUE THREAD

**Issue by SarojMaharjan** [superpeteblaze/ScalingCarousel#56]
I am trying to implement the scalingcarousel in an app which should support ios 9.0. I saw this library requirement was 9 but when i tried installing it over pod I encountered following errors:

[!] CocoaPods could not find compatible versions for pod "ScalingCarousel":
  In snapshot (Podfile.lock):
    ScalingCarousel (= 2.4.1)

  In Podfile:
    ScalingCarousel

Specs satisfying the `ScalingCarousel, ScalingCarousel (= 2.4.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by superpeteblaze** [comment]
Hi @SarojMaharjan. The library now requires iOS 10. I overlooked updating the readme when I made this change, but have updated the readme now.
