### ISSUE TITLE
'UICollectionViewScrollPosition' has been renamed to 'UICollectionView.ScrollPosition'

### ISSUE THREAD

**Issue by ppshein** [superpeteblaze/ScalingCarousel#58]
`/Users/user/Documents/Projects/iOS/WavePay/Pods/ScalingCarousel/ScalingCarousel/Classes/ScalingCarouselView.swift:119:81: 'UICollectionViewScrollPosition' has been renamed to 'UICollectionView.ScrollPosition'`

Not currently compatible to `swift 4.2`

**Comment by superpeteblaze** [comment]
Migrated to Swift 5
