### ISSUE TITLE
Wrong cell position after navigation

### ISSUE THREAD

**Issue by omate94** [superpeteblaze/ScalingCarousel#61]
After navigation the cell is not centered. Just after I add scaling carousel view inset.

**Comment by dogo** [comment]
https://github.com/superpeteblaze/ScalingCarousel/issues/53#issuecomment-442558875
Patch

**Comment by Rahul379** [comment]
Still facing issue for second cell, but working fine for other cells.
When on second cell after navigating back cell is centered but row value is return 0 which should be 1.

**Comment by superpeteblaze** [comment]
As per the readme 

> Set your UIViewController as the collection view delegate and implement the UIScrollViewDelegate method scrollViewDidScroll(:). In this method, call the didScroll() method of ScalingCarouselView
