### ISSUE TITLE
EXC_BAD_ACCESS when calling customViewName.didScroll() in scrollViewDidScroll 

### ISSUE THREAD

**Issue by mozead1996** [superpeteblaze/ScalingCarousel#62]
![Screen Shot 2019-06-14 at 11 22 05 PM](https://user-images.githubusercontent.com/26047721/59539692-83779380-8efe-11e9-8682-0dd7fa550829.png)

**Comment by mohamedzead1996** [comment]
collectionView here is the outlet of scaling carousel in my controller

**Comment by superpeteblaze** [comment]
This error code usually means we are trying to access something which has already been deallocated.

As a starting point, try the debugging tips outlined here - https://code.tutsplus.com/tutorials/what-is-exc_bad_access-and-how-to-debug-it--cms-24544

**Comment by superpeteblaze** [comment]
Cannot reproduce
