### ISSUE TITLE
Multiple Prototype collection view cells have the same identifier: cell

### ISSUE THREAD

**Issue by GeoffGodwin** [superpeteblaze/ScalingCarousel#63]
While using Xcode 10.2.1 and attempting to run the example project I am met with this error:
`Multiple Prototype collection view cells have the same identifier: cell`
Whenever the carousel has more than a single cell in it. 

While attempting to implement this library into my own project I've come across the same issue and am unable to build the project with more than one cell so long as the Collection Reusable view identifier is "cell" in all of them. Note: that I am using the storyboard method at the moment and will be attempting the code method while awaiting a reply.

I am very new to Swift development coming over from Android development and may just be missing something simple here but I am open to ideas.

Thank you for making this lib!

**Comment by GeoffGodwin** [comment]
Can confirm, programmatic addition of cells with the same "forCellWithReuseIdentifier" in swift is working as expected. So it's just the storyboard method that appears to take issue.

**Comment by superpeteblaze** [comment]
Thanks for reporting this @GeoffGodwin. 

At the moment, I've no estimation for when I can get this issue addressed. If you manage at any point to find a solution, please do open a PR.

**Comment by superpeteblaze** [comment]
Cannot reproduce in Xcode 11.4
