### ISSUE TITLE
Swift 5 support?

### ISSUE THREAD

**Issue by muehlemann** [superpeteblaze/ScalingCarousel#64]
Hi, wondering if there are plans to add Swift 5 support?

**Comment by superpeteblaze** [comment]
Hi @muehlemann, It's definitely something that would be great to add. However, I don't have the time to do this right now, but if you or someone else would like to open a PR, that would be fantastic.

**Comment by muehlemann** [comment]
@superpeteblaze Heres a PR: https://github.com/superpeteblaze/ScalingCarousel/pull/65

**Comment by superpeteblaze** [comment]
Awesome, thanks @muehlemann

**Comment by muehlemann** [comment]
@superpeteblaze Can you please create a release tag so that the swift five update is available via cocoapods. Once that is done I think we can close this issue.

**Comment by superpeteblaze** [comment]
@muehlemann The build was failing locally for me, so I redid the migration. v3.0 has been released.

Note that I also undid the iOS 9 support, as I have not had time to test that.
