### ISSUE TITLE
Corner radius changing

### ISSUE THREAD

**Issue by XFactorus** [superpeteblaze/ScalingCarousel#75]
Hello,

Can we please make "cornerRadius" property in "ScalingCarouselCell"  class public?

It will allow updating view for user needs and design and should not break anything.

The fix is pretty easy in ScalingCarouselCell.swift:

    open var cornerRadius: CGFloat = 20.0
    ...
    mainView.layer.cornerRadius = 20

Thanks!

**Comment by superpeteblaze** [comment]
@XFactorus PR opened and linked

**Comment by XFactorus** [comment]
Sorry for the long reply.

Looks great, thanks
