### ISSUE TITLE
The first and the last Cell, don't be called in willDisplay method

### ISSUE THREAD

**Issue by hengchengfei** [superpeteblaze/ScalingCarousel#8]
in 'willDisplay' method ,when scroll to the first cell or the last cell,not be called.

indexpath.row is not correct.

<img width="1203" alt="screen shot 2017-05-12 at 12 00 59 pm" src="https://cloud.githubusercontent.com/assets/3182964/25981895/c0bbd222-370a-11e7-9b71-ae9ea9ac9a47.png">

**Comment by superpeteblaze** [comment]
@hengchengfei Are you still experiencing this issue? Or have you found a cause/solution?

**Comment by superpeteblaze** [comment]
@hengchengfei Looking in to this a bit - I believe what we are seeing is normal behaviour. The 'willDisplay' method is called when cells are added to the collection view (ScalingCarousel). This means that if the cell is already present, it won't be called. 

Does this make sense?
